1322|shellfish|NEW ZEALAND GREEN LIPPED MUSSELS
1323|hors-doeuvres|PETIT CROLINES
1327|fish|ARBROATH SMOKIES
1329|fish|ATLANTIC SALMON FILLETS
1330|buffet-starters|BARBECUE RIBS
1330|meat-specialities|BARBECUE RIBS
1332|meat-specialities|BEEF WELLINGTON
1333|fish-specialities|BEER-BATTERED COD FILLETS
1335|childrens|BEER BATTERED COD GOUJONS
1335|fish-specialities|BEER BATTERED COD GOUJONS
1337|buffet-starters|BLANCHBAIT
1345|meat-poultry|BRITISH BEEF STEAK MINCE
1347|gluten-free|BRITISH ORANGE & BASIL DUCK
1347|poultry-specialities|BRITISH ORANGE & BASIL DUCK
1349|gluten-free|BRITISH ROSEMARY AND GARLIC DUCK
1349|poultry-specialities|BRITISH ROSEMARY AND GARLIC DUCK
1350|poultry-specialities|CAJUN CHICKEN
1351|shellfish|CANADIAN ROELESS KING SCALLOPS
1352|buffet-starters|CANNELLONI BOLOGNESE VERDI
1353|vegetarian|CANNELLONI VERDI
1355|poultry-specialities|CHEESE AND SPRING ONION CHICKEN
1357|poultry-specialities|CHICKEN BALINT
1372|childrens|CHICKEN KEBABS
1372|gluten-free|CHICKEN KEBABS
1374|on-sale|CHICKEN KIEV
1376|poultry-specialities|BRITISH CHICKEN TENDERLOINS
1381|shellfish|COCKLES
1389|fish-specialities|COD AND PANCETTA HAM FISHCAKES
1391|buffet-starters|COQUILLES SAINT-JACQUES
1391|fish-specialities|COQUILLES SAINT-JACQUES
1398|buffet-starters|CRISPY DUCK SPRING ROLLS
1398|hors-doeuvres|CRISPY DUCK SPRING ROLLS
1402|meat-poultry|DEVON FREE RANGE DUCK BREASTS
1404|on-sale|DEVON DRESSED CRAB
1404|shellfish|DEVON DRESSED CRAB
1405|on-sale|AGED SIRLOIN STEAK
1407|meat-specialities|DUCK CONFIT
1413|buffet-starters|FILO KING PRAWNS
1417|shellfish|GAMBAS
1439|shellfish|GARLIC KING PRAWNS
1442|meat-specialities|GLAZED GAMMON HOCK
1445|shellfish|GOURMET SCAMPI
1450|meat-specialities|HONEY LAMB ROASTS
1452|childrens|CRISPY BATTERED COD FISH FINGERS
1456|fish-specialities|KILN-ROASTED SCOTTISH SMOKED SALMON SELECTION
1458|shellfish|KING PRAWNS
1460|meat-specialities|LAMB KOFTAS
1462|shellfish|LARGE, WHOLE CLAMS
1472|childrens|LINCOLNSHIRE FISHCAKES
1473|shellfish|LOBSTER TAILS
1474|shellfish|LUXURY SALAD PRAWNS
1476|fish|MAHI MAHI SUPREMES
1479|fish|NEW ZEALAND DORY FILLETS
1481|fish|NEW ZEALAND MONKFISH (Stargazer)
1483|fish|NORTH ATLANTIC HALIBUT STEAKS
1487|fish|NORWEGIAN WILD COD LOINS
1490|shellfish|OVEN BAKE WHOLE TAIL SCAMPI
1491|fish-specialities|PAELLA
1500|shellfish|EASY PEEL RAW KING PRAWNS
1504|gluten-free|ROSEMARY & GARLIC PORK
1509|childrens|SALMON SHANTIS
1520|childrens|SMOKED HADDOCK FISHCAKES
1524|childrens|SOUTHERN FRIED CHICKEN FILLETS
2163|fish|CORNISH ALBACORE TUNA LOINS
2163|on-sale|CORNISH ALBACORE TUNA LOINS
2183|meat-poultry|CARVERY SELECTION
2183|meat-specialities|CARVERY SELECTION
2186|desserts|BAILEYS CHEESECAKE
2187|desserts|APPLE AND BLACKBERRY CRUNCH
2188|desserts|APPLE AND PEAR PUDDING
2197|buffet-starters|CRISPY COATED KING PRAWNS
2197|on-sale|CRISPY COATED KING PRAWNS
2197|shellfish|CRISPY COATED KING PRAWNS
2205|fish|GROUPER FILLET
2208|fish-specialities|BREADED PLAICE FILLETS
2208|fish|BREADED PLAICE FILLETS
2208|on-sale|BREADED PLAICE FILLETS
2209|childrens|CRISPY BREADED COD FISH FINGERS
2228|meat-poultry|BARBARY DUCK BREASTS
2228|on-sale|BARBARY DUCK BREASTS
2230|meat-specialities|BRITISH PEPPERED BEEF RUMP STEAKS
2232|meat-poultry|BRITISH ROSE VEAL
2233|shellfish|RAW PEELED KING PRAWNS
2241|fish|MARLIN SUPREMES
2243|desserts|DESSERT CANAPES
2245|on-sale|COQUILLES DE MAR
2247|fish|FAROE SALMON SUPREME
2475|meat-poultry|BRITISH CORN FED CHICKEN SUPREMES
2481|vegetarian|VEGETABLE KIEV
2577|meat-specialities|TURKEY AND CRANBERRY ROLLED CROWNS
2577|poultry-specialities|TURKEY AND CRANBERRY ROLLED CROWNS
2592|meat-poultry|WEST COUNTRY DICED BUTCHERS SELECTION
2592|on-sale|WEST COUNTRY DICED BUTCHERS SELECTION
2595|meat-poultry|PRIME DEVON BEEFBURGERS
2595|meat-specialities|PRIME DEVON BEEFBURGERS
2599|meat-poultry|BARNSLEY LAMB CHOPS MINTED
2602|fish|CAPE HAKE FILLETS
2602|on-sale|CAPE HAKE FILLETS
2605|fish-specialities|BASA SELECTIONS
2608|desserts|CRUNCH SELECTION
2611|vegetarian|VEGETERIAN WELLINGTONS SELECTION
2612|poultry-specialities|BRITISH TURKEY SUPREMES
2619|poultry-specialities|STILTON & SOUR CREAM TURKEY BREAST
2622|fish-specialities|CRISPY BATTERED HADDOCK FILLET
2622|on-sale|CRISPY BATTERED HADDOCK FILLET
2630|gluten-free|CHINESE PLUM DUCK BREASTS
2630|poultry-specialities|CHINESE PLUM DUCK BREASTS
2650|buffet-starters|CHEESE AND BACON SHANTIS
2650|childrens|CHEESE AND BACON SHANTIS
2650|on-sale|CHEESE AND BACON SHANTIS
2974|childrens|HANDMADE FISHCAKES SELECTION
2974|fish-specialities|HANDMADE FISHCAKES SELECTION
2982|buffet-starters|CRISPY LEMON SOLE GOUJONS
2982|childrens|CRISPY LEMON SOLE GOUJONS
2982|fish-specialities|CRISPY LEMON SOLE GOUJONS
2995|gluten-free|GLUTEN FREE FISH FINGERS
3044|desserts|TRIO OF CHOCOLATE
3155|meat-poultry|SWEET CHILLI CHICKEN
3155|poultry-specialities|SWEET CHILLI CHICKEN
3158|fish-specialities|SOLE SELECTION
3162|meat-specialities|CLASSIC BBQ SELECTION
3165|childrens|GOURMET SALMON BURGERS
3165|fish-specialities|GOURMET SALMON BURGERS
3168|fish-specialities|GOURMET FISH SELECTION
3172|poultry-specialities|CHINESE CHICKEN KEBABS
3174|meat-poultry|PORK SELECTION
3174|meat-specialities|PORK SELECTION
3239|poultry-specialities|GOURMET KIEVS SELECTION
3243|fish|TURBOT FILLET
3243|on-sale|TURBOT FILLET
3246|meat-poultry|AGED WAGYU BEEF JOINTS
3246|meat-specialities|AGED WAGYU BEEF JOINTS
3248|meat-poultry|WAGYU SIRLOIN STEAK
3248|on-sale|WAGYU SIRLOIN STEAK
3273|poultry-specialities|CHICKEN & PORT WELLINGTON
3296|fish-specialities|HADDOCK SELECTION
3303|fish|SEA TROUT SUPREMES
3321|buffet-starters|ORIENTAL DIM SUM SELECTION
3333|buffet-starters|VEGETARIAN SPRING ROLLS
3333|hors-doeuvres|VEGETARIAN SPRING ROLLS
3337|buffet-starters|WEST COUNTRY PATES SELECTION
3337|gluten-free|WEST COUNTRY PATES SELECTION
3337|on-sale|WEST COUNTRY PATES SELECTION
3423|meat-poultry|ANGUS STEAK BEEFBURGERS SELECTION
3423|meat-specialities|ANGUS STEAK BEEFBURGERS SELECTION
3425|meat-specialities|OUTDOOR REARED STUFFED PORK CHOPS